=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/simple-wsd-doc.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT SimpleWsdDoc (word*) >
<!ATTLIST SimpleWsdDoc name CDATA #REQUIRED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word text CDATA #REQUIRED>
<!ATTLIST word break_level CDATA #REQUIRED>
<!ATTLIST word lemma CDATA #IMPLIED>
<!ATTLIST word pos CDATA #IMPLIED>
<!ATTLIST word sense CDATA #IMPLIED>

=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/written/spam/ucb54.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SimpleWsdDoc SYSTEM "simple-wsd-doc.dtd">
<SimpleWsdDoc name="/written/spam/ucb54.txt">
  <word text="/" break_level="NO_BREAK"/>
  <word text="written" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="spam" lemma="spam" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1292742.002" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="ucb54.txt" break_level="NO_BREAK"/>
  <word text="From" break_level="PARAGRAPH_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Good" lemma="good" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1251501.001" break_level="SENTENCE_BREAK"/>
  <word text="Erection" lemma="erection" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1244701.003" break_level="SPACE_BREAK"/>
  <word text="To" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="xxx@xxx.xxx" break_level="SPACE_BREAK"/>
  <word text="Subject" lemma="subject" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1295267.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="The" break_level="SENTENCE_BREAK"/>
  <word text="problem" lemma="problem" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1280894.001" break_level="SPACE_BREAK"/>
  <word text="has" lemma="have" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1253820.001" break_level="SPACE_BREAK"/>
  <word text="gone" lemma="go" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1251252.015" break_level="SPACE_BREAK"/>
  <word text="with" break_level="SPACE_BREAK"/>
  <word text="VIAGRA" break_level="SPACE_BREAK"/>
  <word text="!" break_level="NO_BREAK"/>
  <word text="Date" lemma="date" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1238437.001" break_level="SENTENCE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Wed" break_level="SENTENCE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="26" break_level="SPACE_BREAK"/>
  <word text="Sep" break_level="SPACE_BREAK"/>
  <word text="2007" break_level="SPACE_BREAK"/>
  <word text="14:22:20" break_level="SPACE_BREAK"/>
  <word text="-0000" break_level="SPACE_BREAK"/>
  <word text="What" break_level="PARAGRAPH_BREAK"/>
  <word text="is" lemma="be" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1225404.008" break_level="SPACE_BREAK"/>
  <word text="Erectile" break_level="SPACE_BREAK"/>
  <word text="Dysfunction" break_level="SPACE_BREAK"/>
  <word text="(" break_level="SPACE_BREAK"/>
  <word text="ED" break_level="NO_BREAK"/>
  <word text=")" break_level="NO_BREAK"/>
  <word text="?" break_level="NO_BREAK"/>
  <word text="Erectile" break_level="SENTENCE_BREAK"/>
  <word text="dysfunction" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="sometimes" break_level="SPACE_BREAK"/>
  <word text="referred" lemma="refer" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1283794.001" break_level="SPACE_BREAK"/>
  <word text="to" break_level="LINE_BREAK"/>
  <word text="as" break_level="SPACE_BREAK"/>
  <word text="impotence" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="is" lemma="be" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1225404.008" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="inability" break_level="SPACE_BREAK"/>
  <word text="for" break_level="SPACE_BREAK"/>
  <word text="a" break_level="SPACE_BREAK"/>
  <word text="sexually" break_level="SPACE_BREAK"/>
  <word text="active" lemma="active" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1219797.005" break_level="SPACE_BREAK"/>
  <word text="male" break_level="SPACE_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="obtain" lemma="obtain" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1272728.001" break_level="SPACE_BREAK"/>
  <word text="and" break_level="LINE_BREAK"/>
  <word text="sustain" lemma="sustain" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1296104.001" break_level="SPACE_BREAK"/>
  <word text="an" break_level="SPACE_BREAK"/>
  <word text="erection" lemma="erection" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1244701.003" break_level="SPACE_BREAK"/>
  <word text="for" break_level="SPACE_BREAK"/>
  <word text="sexual" lemma="sexual" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1289518.001" break_level="SPACE_BREAK"/>
  <word text="purposes" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="In" break_level="SENTENCE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="past" lemma="past" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1275970.005" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="this" break_level="SPACE_BREAK"/>
  <word text="has" lemma="have" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1253820.034" break_level="SPACE_BREAK"/>
  <word text="been" break_level="SPACE_BREAK"/>
  <word text="very" break_level="LINE_BREAK"/>
  <word text="embarrassing" break_level="SPACE_BREAK"/>
  <word text="for" break_level="SPACE_BREAK"/>
  <word text="men" lemma="man" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1265688.001" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="a" break_level="SPACE_BREAK"/>
  <word text="source" break_level="SPACE_BREAK"/>
  <word text="of" break_level="SPACE_BREAK"/>
  <word text="anxiety" break_level="SPACE_BREAK"/>
  <word text="for" break_level="SPACE_BREAK"/>
  <word text="their" break_level="SPACE_BREAK"/>
  <word text="partners" lemma="partner" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1275836.001" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="and" break_level="LINE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="in" break_level="SPACE_BREAK"/>
  <word text="fact" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="there" break_level="SPACE_BREAK"/>
  <word text="has" lemma="have" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1253820.034" break_level="SPACE_BREAK"/>
  <word text="been" break_level="SPACE_BREAK"/>
  <word text="very" break_level="SPACE_BREAK"/>
  <word text="little" break_level="SPACE_BREAK"/>
  <word text="diagnostic" lemma="diagnostic" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1240059.001" break_level="SPACE_BREAK"/>
  <word text="testing" lemma="test" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1297943.001" break_level="SPACE_BREAK"/>
  <word text="or" break_level="SPACE_BREAK"/>
  <word text="treatments" break_level="SPACE_BREAK"/>
  <word text="available" break_level="LINE_BREAK"/>
  <word text="up" break_level="SPACE_BREAK"/>
  <word text="until" break_level="SPACE_BREAK"/>
  <word text="very" break_level="SPACE_BREAK"/>
  <word text="recently.But" break_level="SPACE_BREAK"/>
  <word text="now" lemma="now" pos="ADV" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1272258.001" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="problem" lemma="problem" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1280894.001" break_level="SPACE_BREAK"/>
  <word text="has" lemma="have" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1253820.001" break_level="SPACE_BREAK"/>
  <word text="gone" lemma="go" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1251252.015" break_level="SPACE_BREAK"/>
  <word text="with" break_level="SPACE_BREAK"/>
  <word text="VIAGRA" break_level="SPACE_BREAK"/>
  <word text="!" break_level="NO_BREAK"/>
  <word text="Buy" lemma="buy" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1229786.001" break_level="SENTENCE_BREAK"/>
  <word text="VIAGRA" break_level="SPACE_BREAK"/>
  <word text="at" break_level="SPACE_BREAK"/>
  <word text="our" break_level="SPACE_BREAK"/>
  <word text="online" break_level="SPACE_BREAK"/>
  <word text="store" lemma="store" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1294689.001" break_level="SPACE_BREAK"/>
  <word text="!" break_level="NO_BREAK"/>
</SimpleWsdDoc>

=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/written/email/lists-003-2144868.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SimpleWsdDoc SYSTEM "simple-wsd-doc.dtd">
<SimpleWsdDoc name="/written/email/lists-003-2144868.txt">
  <word text="/" break_level="NO_BREAK"/>
  <word text="written" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="email" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="lists" lemma="list" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1263771.001" break_level="NO_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="003" break_level="NO_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="2144868.txt" break_level="NO_BREAK"/>
  <word text="docno" break_level="PARAGRAPH_BREAK"/>
  <word text="=" break_level="NO_BREAK"/>
  <word text="``" break_level="NO_BREAK"/>
  <word text="lists" break_level="NO_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="003" break_level="NO_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="2144868" break_level="NO_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="received" lemma="receive" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1283407.001" break_level="LINE_BREAK"/>
  <word text="=" break_level="NO_BREAK"/>
  <word text="``" break_level="NO_BREAK"/>
  <word text="Tue" break_level="NO_BREAK"/>
  <word text="May" break_level="SPACE_BREAK"/>
  <word text="18" break_level="SPACE_BREAK"/>
  <word text="20:20:31" break_level="SPACE_BREAK"/>
  <word text="1993" break_level="SPACE_BREAK"/>
  <word text="EST" break_level="SPACE_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="sent" lemma="send" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1289024.001" break_level="LINE_BREAK"/>
  <word text="=" break_level="NO_BREAK"/>
  <word text="``" break_level="NO_BREAK"/>
  <word text="Wed" break_level="NO_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="19" break_level="SPACE_BREAK"/>
  <word text="May" break_level="SPACE_BREAK"/>
  <word text="1993" break_level="SPACE_BREAK"/>
  <word text="12:17:09" break_level="SPACE_BREAK"/>
  <word text="+0900" break_level="SPACE_BREAK"/>
  <word text="(" break_level="SPACE_BREAK"/>
  <word text="JST" break_level="NO_BREAK"/>
  <word text=")" break_level="NO_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="name" lemma="name" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1270390.001" break_level="LINE_BREAK"/>
  <word text="=" break_level="NO_BREAK"/>
  <word text="``" break_level="NO_BREAK"/>
  <word text="Masataka" break_level="NO_BREAK"/>
  <word text="Ohta" break_level="SPACE_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="email" break_level="LINE_BREAK"/>
  <word text="=" break_level="NO_BREAK"/>
  <word text="``" break_level="NO_BREAK"/>
  <word text="mohta@necom830.cc.titech.ac.jp" break_level="NO_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="subject" lemma="subject" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1295267.001" break_level="LINE_BREAK"/>
  <word text="=" break_level="NO_BREAK"/>
  <word text="``" break_level="NO_BREAK"/>
  <word text="Re" break_level="NO_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="CHARSET" break_level="SENTENCE_BREAK"/>
  <word text="considerations" lemma="consideration" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1235479.001" break_level="SPACE_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="id" break_level="LINE_BREAK"/>
  <word text="=" break_level="NO_BREAK"/>
  <word text="``" break_level="NO_BREAK"/>
  <word text="9305190317.AA01493" break_level="NO_BREAK"/>
  <word text="@" break_level="NO_BREAK"/>
  <word text="necom830.cc.titech.ac.jp" break_level="NO_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="inreplyto" break_level="LINE_BREAK"/>
  <word text="=" break_level="NO_BREAK"/>
  <word text="``" break_level="NO_BREAK"/>
  <word text="01GYBXHRZVEA8Y5JAE" break_level="NO_BREAK"/>
  <word text="@" break_level="NO_BREAK"/>
  <word text="INNOSOFT.COM" break_level="NO_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="To" break_level="PARAGRAPH_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="TROTH@ricevm1.rice.edu" break_level="SENTENCE_BREAK"/>
  <word text="(" break_level="SPACE_BREAK"/>
  <word text="Rick" break_level="NO_BREAK"/>
  <word text="Troth" break_level="SPACE_BREAK"/>
  <word text=")" break_level="NO_BREAK"/>
  <word text="Cc" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="scs@adam.mit.edu" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="pine" break_level="SPACE_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="info@cac.washington.edu" break_level="NO_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="ietf" break_level="SPACE_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="charsets@INNOSOFT.COM" break_level="NO_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="I" break_level="PARAGRAPH_BREAK"/>
  <word text="do" lemma="do" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1241237.035" break_level="SPACE_BREAK"/>
  <word text="n&#39;t" break_level="NO_BREAK"/>
  <word text="know" lemma="know" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1261363.001" break_level="SPACE_BREAK"/>
  <word text="what" break_level="SPACE_BREAK"/>
  <word text="pine" break_level="SPACE_BREAK"/>
  <word text="is" lemma="be" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1225404.008" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="But" break_level="PARAGRAPH_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="could" lemma="could" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1236433.001" break_level="SPACE_BREAK"/>
  <word text="you" break_level="SPACE_BREAK"/>
  <word text="please" break_level="SPACE_BREAK"/>
  <word text="discuss" break_level="SPACE_BREAK"/>
  <word text="on" break_level="SPACE_BREAK"/>
  <word text="pine" break_level="SPACE_BREAK"/>
  <word text="specific" lemma="specific" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1292910.001" break_level="SPACE_BREAK"/>
  <word text="features" lemma="feature" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1246503.001" break_level="SPACE_BREAK"/>
  <word text="in" break_level="SPACE_BREAK"/>
  <word text="pine" break_level="SPACE_BREAK"/>
  <word text="ML" break_level="SPACE_BREAK"/>
  <word text="only" lemma="only" pos="ADV" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1273443.001" break_level="LINE_BREAK"/>
  <word text="?" break_level="NO_BREAK"/>
  <word text="Masataka" break_level="PARAGRAPH_BREAK"/>
  <word text="Ohta" break_level="SPACE_BREAK"/>
</SimpleWsdDoc>

=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/written/email/219257.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SimpleWsdDoc SYSTEM "simple-wsd-doc.dtd">
<SimpleWsdDoc name="/written/email/219257.txt">
  <word text="/" break_level="NO_BREAK"/>
  <word text="written" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="email" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="219257.txt" break_level="NO_BREAK"/>
  <word text="Message" lemma="message" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1267368.001" break_level="PARAGRAPH_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="ID" lemma="ID" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1256893.003" break_level="NO_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Date" lemma="date" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1238437.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Thu" break_level="SENTENCE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="30" break_level="SPACE_BREAK"/>
  <word text="Aug" break_level="SPACE_BREAK"/>
  <word text="2001" break_level="SPACE_BREAK"/>
  <word text="13:32:27" break_level="SPACE_BREAK"/>
  <word text="-0700" break_level="SPACE_BREAK"/>
  <word text="(" break_level="SPACE_BREAK"/>
  <word text="PDT" break_level="NO_BREAK"/>
  <word text=")" break_level="NO_BREAK"/>
  <word text="From" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="alan.comnes@enron.com" break_level="SPACE_BREAK"/>
  <word text="To" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="e-mail" break_level="SPACE_BREAK"/>
  <word text="," break_level="SPACE_BREAK"/>
  <word text="ray.alvarez@enron.com" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="robert.frank@enron.com" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="tim.belden@enron.com" break_level="PARAGRAPH_BREAK"/>
  <word text="Subject" lemma="subject" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1295267.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Refund" break_level="SENTENCE_BREAK"/>
  <word text="Cases" break_level="SPACE_BREAK"/>
  <word text="Timelines" break_level="SPACE_BREAK"/>
  <word text="--" break_level="NO_BREAK"/>
  <word text="Confidential" break_level="SENTENCE_BREAK"/>
  <word text="Atty" break_level="SPACE_BREAK"/>
  <word text="Client" break_level="SPACE_BREAK"/>
  <word text="Work" break_level="SPACE_BREAK"/>
  <word text="Product" break_level="SPACE_BREAK"/>
  <word text="Cc" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="d." break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="steffes@enron.com" break_level="SENTENCE_BREAK"/>
  <word text="Mime" break_level="LINE_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="Version" lemma="version" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1303957.001" break_level="NO_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="1.0" break_level="SPACE_BREAK"/>
  <word text="Content" lemma="content" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1235616.001" break_level="LINE_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="Type" lemma="type" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1301323.001" break_level="NO_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="text" lemma="text" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1298051.001" break_level="SPACE_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="plain" break_level="NO_BREAK"/>
  <word text=";" break_level="NO_BREAK"/>
  <word text="charset" break_level="SPACE_BREAK"/>
  <word text="=" break_level="NO_BREAK"/>
  <word text="us" break_level="NO_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="ascii" break_level="NO_BREAK"/>
  <word text="Content" lemma="content" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1235616.001" break_level="LINE_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="Transfer" lemma="transfer" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1299918.010" break_level="NO_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="Encoding" break_level="NO_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="7bit" break_level="SPACE_BREAK"/>
  <word text="Bcc" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="d." break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="steffes@enron.com" break_level="SENTENCE_BREAK"/>
  <word text="Tim" break_level="PARAGRAPH_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="Per" break_level="PARAGRAPH_BREAK"/>
  <word text="your" break_level="SPACE_BREAK"/>
  <word text="request" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Everybody" break_level="PARAGRAPH_BREAK"/>
  <word text="else" break_level="SPACE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="please" break_level="SPACE_BREAK"/>
  <word text="forward" lemma="forward" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1248624.022" break_level="SPACE_BREAK"/>
  <word text="corrections" break_level="SPACE_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="updates" break_level="NO_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="me" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Thanks" break_level="PARAGRAPH_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="Alan" break_level="PARAGRAPH_BREAK"/>
  <word text="Comnes" break_level="SPACE_BREAK"/>
</SimpleWsdDoc>

=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/written/spam/ucb21.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SimpleWsdDoc SYSTEM "simple-wsd-doc.dtd">
<SimpleWsdDoc name="/written/spam/ucb21.txt">
  <word text="/" break_level="NO_BREAK"/>
  <word text="written" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="spam" lemma="spam" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1292742.002" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="ucb21.txt" break_level="NO_BREAK"/>
  <word text="From" break_level="PARAGRAPH_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="``" break_level="SPACE_BREAK"/>
  <word text="chet" break_level="NO_BREAK"/>
  <word text="heidi" break_level="SPACE_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="To" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Subject" lemma="subject" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1295267.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="spring" lemma="spring" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1293466.015" break_level="SPACE_BREAK"/>
  <word text="selection" lemma="selection" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1288633.001" break_level="SPACE_BREAK"/>
  <word text="Date" lemma="date" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1238437.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Wed" break_level="SENTENCE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="17" break_level="SPACE_BREAK"/>
  <word text="Mar" break_level="SPACE_BREAK"/>
  <word text="2010" break_level="SPACE_BREAK"/>
  <word text="05:29:10" break_level="SPACE_BREAK"/>
  <word text="+0000" break_level="SPACE_BREAK"/>
  <word text="Detailed" lemma="detailed" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1239807.001" break_level="PARAGRAPH_BREAK"/>
  <word text="quality" break_level="SPACE_BREAK"/>
  <word text="replicas" break_level="SPACE_BREAK"/>
  <word text="of" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="most" lemma="most" pos="ADV" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1269360.005" break_level="SPACE_BREAK"/>
  <word text="wanted" break_level="SPACE_BREAK"/>
  <word text="designer" break_level="SPACE_BREAK"/>
  <word text="watches" lemma="watch" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1305222.010" break_level="SPACE_BREAK"/>
  <word text="are" break_level="SPACE_BREAK"/>
  <word text="here" lemma="here" pos="ADV" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1254554.001" break_level="SPACE_BREAK"/>
  <word text="!" break_level="NO_BREAK"/>
  <word text="genuine" break_level="LINE_BREAK"/>
  <word text="solid" lemma="solid" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1292245.001" break_level="SPACE_BREAK"/>
  <word text="stainless" break_level="SPACE_BREAK"/>
  <word text="steel" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="99.9" break_level="SPACE_BREAK"/>
  <word text="%" break_level="NO_BREAK"/>
  <word text="accurate" lemma="accurate" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1219600.001" break_level="SPACE_BREAK"/>
  <word text="markings" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="finish" lemma="finish" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1247159.011" break_level="SPACE_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="=" break_level="SPACE_BREAK"/>
  <word text="weight" lemma="weight" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1305598.001" break_level="LINE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="-" break_level="SENTENCE_BREAK"/>
  <word text="The" break_level="SPACE_BREAK"/>
  <word text="worlds" lemma="world" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1307108.001" break_level="SPACE_BREAK"/>
  <word text="largest" lemma="large" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1262244.001" break_level="SPACE_BREAK"/>
  <word text="online" break_level="SPACE_BREAK"/>
  <word text="retailer" break_level="SPACE_BREAK"/>
  <word text="of" break_level="SPACE_BREAK"/>
  <word text="luxury" break_level="SPACE_BREAK"/>
  <word text="products" lemma="product" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1280957.001" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="including" lemma="include" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1257529.001" break_level="SPACE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Rolex" break_level="SENTENCE_BREAK"/>
  <word text="Sports" break_level="SPACE_BREAK"/>
  <word text="Models" lemma="model" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1268618.009" break_level="SPACE_BREAK"/>
  <word text="Rolex" break_level="LINE_BREAK"/>
  <word text="Datejusts" break_level="SPACE_BREAK"/>
  <word text="Breitling" break_level="LINE_BREAK"/>
  <word text="Cartier" break_level="LINE_BREAK"/>
  <word text="Porsche" break_level="LINE_BREAK"/>
  <word text="Design" break_level="SPACE_BREAK"/>
  <word text="Dolce" break_level="LINE_BREAK"/>
  <word text="&amp;" break_level="SPACE_BREAK"/>
  <word text="Gabbana" break_level="SPACE_BREAK"/>
  <word text="Dior" break_level="LINE_BREAK"/>
  <word text="Gucci" break_level="LINE_BREAK"/>
  <word text="Hermes" break_level="LINE_BREAK"/>
  <word text="Watches" break_level="SPACE_BREAK"/>
  <word text="Patek" break_level="LINE_BREAK"/>
  <word text="Philippe" break_level="SPACE_BREAK"/>
  <word text="Visit" break_level="LINE_BREAK"/>
  <word text="-" break_level="SPACE_BREAK"/>
  <word text="www.devasiess.com" break_level="SPACE_BREAK"/>
</SimpleWsdDoc>
