=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/simple-wsd-doc.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT SimpleWsdDoc (word*) >
<!ATTLIST SimpleWsdDoc name CDATA #REQUIRED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word text CDATA #REQUIRED>
<!ATTLIST word break_level CDATA #REQUIRED>
<!ATTLIST word lemma CDATA #IMPLIED>
<!ATTLIST word pos CDATA #IMPLIED>
<!ATTLIST word sense CDATA #IMPLIED>

=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/written/spam/ucb26.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SimpleWsdDoc SYSTEM "simple-wsd-doc.dtd">
<SimpleWsdDoc name="/written/spam/ucb26.txt">
  <word text="/" break_level="NO_BREAK"/>
  <word text="written" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="spam" lemma="spam" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1292742.002" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="ucb26.txt" break_level="NO_BREAK"/>
  <word text="To" break_level="PARAGRAPH_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Subject" lemma="subject" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1295267.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="RE" break_level="SENTENCE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Dear" lemma="dear" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1238652.001" break_level="SENTENCE_BREAK"/>
  <word text="xxx@xxx.xxx" break_level="SPACE_BREAK"/>
  <word text="83" break_level="SPACE_BREAK"/>
  <word text="%" break_level="NO_BREAK"/>
  <word text="0FF" break_level="SPACE_BREAK"/>
  <word text="From" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="VIAGRA" break_level="SENTENCE_BREAK"/>
  <word text="Ã†" break_level="SPACE_BREAK"/>
  <word text="Official" break_level="SPACE_BREAK"/>
  <word text="Site" lemma="site" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1291008.004" break_level="SPACE_BREAK"/>
  <word text="Date" lemma="date" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1238437.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Tue" break_level="SENTENCE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="1" break_level="SPACE_BREAK"/>
  <word text="Jul" break_level="SPACE_BREAK"/>
  <word text="2008" break_level="SPACE_BREAK"/>
  <word text="12:49:59" break_level="SPACE_BREAK"/>
  <word text="-0700" break_level="SPACE_BREAK"/>
  <word text="(" break_level="SPACE_BREAK"/>
  <word text="PDT" break_level="NO_BREAK"/>
  <word text=")" break_level="NO_BREAK"/>
  <word text="About" break_level="PARAGRAPH_BREAK"/>
  <word text="this" break_level="SPACE_BREAK"/>
  <word text="mailing" lemma="mailing" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1265401.001" break_level="SPACE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="You" break_level="PARAGRAPH_BREAK"/>
  <word text="are" lemma="be" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1225404.014" break_level="SPACE_BREAK"/>
  <word text="receiving" lemma="receive" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1283407.001" break_level="SPACE_BREAK"/>
  <word text="this" break_level="SPACE_BREAK"/>
  <word text="e-mail" break_level="SPACE_BREAK"/>
  <word text="because" break_level="SPACE_BREAK"/>
  <word text="you" break_level="SPACE_BREAK"/>
  <word text="subscribed" lemma="subscribe" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1295349.001" break_level="SPACE_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="MSN" break_level="SPACE_BREAK"/>
  <word text="Featured" break_level="SPACE_BREAK"/>
  <word text="Offers" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Microsoft" break_level="SENTENCE_BREAK"/>
  <word text="respects" break_level="SPACE_BREAK"/>
  <word text="your" break_level="SPACE_BREAK"/>
  <word text="privacy" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="If" break_level="SENTENCE_BREAK"/>
  <word text="you" break_level="SPACE_BREAK"/>
  <word text="do" lemma="do" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1241237.035" break_level="SPACE_BREAK"/>
  <word text="not" break_level="LINE_BREAK"/>
  <word text="wish" break_level="SPACE_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="receive" lemma="receive" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1283407.001" break_level="SPACE_BREAK"/>
  <word text="this" break_level="SPACE_BREAK"/>
  <word text="MSN" break_level="SPACE_BREAK"/>
  <word text="Featured" break_level="SPACE_BREAK"/>
  <word text="Offers" break_level="SPACE_BREAK"/>
  <word text="e-mail" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="please" break_level="SPACE_BREAK"/>
  <word text="click" lemma="click" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1233681.004" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="``" break_level="SPACE_BREAK"/>
  <word text="Unsubscribe" break_level="NO_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="link" lemma="link" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1263659.001" break_level="SPACE_BREAK"/>
  <word text="below" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="This" break_level="SENTENCE_BREAK"/>
  <word text="will" break_level="SPACE_BREAK"/>
  <word text="not" break_level="SPACE_BREAK"/>
  <word text="unsubscribe" break_level="LINE_BREAK"/>
  <word text="you" break_level="SPACE_BREAK"/>
  <word text="from" break_level="SPACE_BREAK"/>
  <word text="e-mail" break_level="SPACE_BREAK"/>
  <word text="communications" lemma="communication" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1234839.001" break_level="SPACE_BREAK"/>
  <word text="from" break_level="SPACE_BREAK"/>
  <word text="third" break_level="SPACE_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="party" break_level="NO_BREAK"/>
  <word text="advertisers" break_level="SPACE_BREAK"/>
  <word text="that" break_level="SPACE_BREAK"/>
  <word text="may" lemma="may" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1266614.001" break_level="SPACE_BREAK"/>
  <word text="appear" lemma="appear" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1222474.001" break_level="SPACE_BREAK"/>
  <word text="in" break_level="SPACE_BREAK"/>
  <word text="MSN" break_level="SPACE_BREAK"/>
  <word text="Feature" lemma="feature" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1246503.001" break_level="SPACE_BREAK"/>
  <word text="Offers" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="This" break_level="SENTENCE_BREAK"/>
  <word text="shall" break_level="LINE_BREAK"/>
  <word text="not" break_level="SPACE_BREAK"/>
  <word text="constitute" lemma="constitute" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1235534.001" break_level="SPACE_BREAK"/>
  <word text="an" break_level="SPACE_BREAK"/>
  <word text="offer" break_level="SPACE_BREAK"/>
  <word text="by" break_level="SPACE_BREAK"/>
  <word text="MSN" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="MSN" break_level="SENTENCE_BREAK"/>
  <word text="shall" break_level="SPACE_BREAK"/>
  <word text="not" break_level="SPACE_BREAK"/>
  <word text="be" lemma="be" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1225404.008" break_level="SPACE_BREAK"/>
  <word text="responsible" break_level="SPACE_BREAK"/>
  <word text="or" break_level="SPACE_BREAK"/>
  <word text="liable" lemma="liable" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1263232.001" break_level="SPACE_BREAK"/>
  <word text="for" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="advertisers" break_level="SPACE_BREAK"/>
  <word text="&#39;" break_level="NO_BREAK"/>
  <word text="content" lemma="content" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1235616.001" break_level="SPACE_BREAK"/>
  <word text="nor" break_level="SPACE_BREAK"/>
  <word text="any" break_level="SPACE_BREAK"/>
  <word text="of" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="goods" lemma="good" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1251501.027" break_level="LINE_BREAK"/>
  <word text="or" break_level="SPACE_BREAK"/>
  <word text="service" break_level="SPACE_BREAK"/>
  <word text="advertised" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Prices" lemma="price" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1280629.001" break_level="SENTENCE_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="item" break_level="SPACE_BREAK"/>
  <word text="availability" break_level="SPACE_BREAK"/>
  <word text="subject" lemma="subject" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1295267.012" break_level="SPACE_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="change" lemma="change" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1232051.001" break_level="SPACE_BREAK"/>
  <word text="without" break_level="SPACE_BREAK"/>
  <word text="notice" lemma="notice" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1272186.002" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Microsoft" break_level="SENTENCE_BREAK"/>
  <word text="Corporation" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="One" break_level="SPACE_BREAK"/>
  <word text="Microsoft" break_level="SPACE_BREAK"/>
  <word text="Way" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="Redmond" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="WA" break_level="SPACE_BREAK"/>
  <word text="98052" break_level="SPACE_BREAK"/>
</SimpleWsdDoc>

=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/written/newspaper_newswire/20000424_nyt-NEW.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SimpleWsdDoc SYSTEM "simple-wsd-doc.dtd">
<SimpleWsdDoc name="/written/newspaper:newswire/20000424_nyt-NEW.txt">
  <word text="/" break_level="NO_BREAK"/>
  <word text="written" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="newspaper" break_level="NO_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="newswire" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="20000424" break_level="NO_BREAK"/>
  <word text="--" break_level="NO_BREAK"/>
  <word text="nyt" break_level="NO_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="NEW.txt" break_level="NO_BREAK"/>
  <word text="IRAQ" break_level="PARAGRAPH_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="POVERTY" break_level="NO_BREAK"/>
  <word text="(" break_level="SPACE_BREAK"/>
  <word text="Washington" break_level="NO_BREAK"/>
  <word text=")" break_level="NO_BREAK"/>
  <word text="Rep." break_level="PARAGRAPH_BREAK"/>
  <word text="Tony" break_level="SPACE_BREAK"/>
  <word text="Hall" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="D" break_level="SPACE_BREAK"/>
  <word text="-" break_level="NO_BREAK"/>
  <word text="Ohio" break_level="NO_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="urges" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="United" break_level="SPACE_BREAK"/>
  <word text="Nations" break_level="SPACE_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="allow" lemma="allow" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1221081.001" break_level="SPACE_BREAK"/>
  <word text="a" break_level="SPACE_BREAK"/>
  <word text="freer" break_level="SPACE_BREAK"/>
  <word text="flow" lemma="flow" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1247899.013" break_level="SPACE_BREAK"/>
  <word text="of" break_level="PARAGRAPH_BREAK"/>
  <word text="food" break_level="SPACE_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="medicine" lemma="medicine" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1266890.002" break_level="SPACE_BREAK"/>
  <word text="into" break_level="SPACE_BREAK"/>
  <word text="Iraq" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Hall" break_level="SENTENCE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="who" break_level="SPACE_BREAK"/>
  <word text="recently" break_level="SPACE_BREAK"/>
  <word text="returned" lemma="return" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1284725.001" break_level="SPACE_BREAK"/>
  <word text="from" break_level="SPACE_BREAK"/>
  <word text="a" break_level="SPACE_BREAK"/>
  <word text="trip" lemma="trip" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1300432.013" break_level="SPACE_BREAK"/>
  <word text="to" break_level="PARAGRAPH_BREAK"/>
  <word text="Iraq" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="said" lemma="say" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1287486.001" break_level="SPACE_BREAK"/>
  <word text="U.N." break_level="SPACE_BREAK"/>
  <word text="economic" lemma="economic" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1243053.001" break_level="SPACE_BREAK"/>
  <word text="sanctions" lemma="sanction" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1286968.001" break_level="SPACE_BREAK"/>
  <word text="have" break_level="SPACE_BREAK"/>
  <word text="hurt" break_level="SPACE_BREAK"/>
  <word text="millions" break_level="SPACE_BREAK"/>
  <word text="of" break_level="SPACE_BREAK"/>
  <word text="civilians" break_level="SPACE_BREAK"/>
  <word text="there" break_level="PARAGRAPH_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="By" break_level="PARAGRAPH_BREAK"/>
  <word text="AUSTIN" break_level="SPACE_BREAK"/>
  <word text="ZALKIN" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
</SimpleWsdDoc>

=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/written/spam/ucb28.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SimpleWsdDoc SYSTEM "simple-wsd-doc.dtd">
<SimpleWsdDoc name="/written/spam/ucb28.txt">
  <word text="/" break_level="NO_BREAK"/>
  <word text="written" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="spam" lemma="spam" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1292742.002" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="ucb28.txt" break_level="NO_BREAK"/>
  <word text="From" break_level="PARAGRAPH_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="``" break_level="SPACE_BREAK"/>
  <word text="jeremiah" break_level="NO_BREAK"/>
  <word text="huntington" break_level="SPACE_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="To" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Subject" lemma="subject" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1295267.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="ID" lemma="ID" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1256893.003" break_level="SENTENCE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="52627" break_level="NO_BREAK"/>
  <word text="Like" break_level="SPACE_BREAK"/>
  <word text="our" break_level="SPACE_BREAK"/>
  <word text="watches" lemma="watch" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1305222.010" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="love" break_level="SPACE_BREAK"/>
  <word text="our" break_level="SPACE_BREAK"/>
  <word text="prices" lemma="price" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1280629.001" break_level="SPACE_BREAK"/>
  <word text="Date" lemma="date" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1238437.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Wed" break_level="SENTENCE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="02" break_level="SPACE_BREAK"/>
  <word text="Jul" break_level="SPACE_BREAK"/>
  <word text="2008" break_level="SPACE_BREAK"/>
  <word text="09:51:41" break_level="SPACE_BREAK"/>
  <word text="+0000" break_level="SPACE_BREAK"/>
  <word text="Speed" lemma="speed" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1292982.010" break_level="PARAGRAPH_BREAK"/>
  <word text="up" break_level="SPACE_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="nightclub" break_level="SPACE_BREAK"/>
  <word text="with" break_level="SPACE_BREAK"/>
  <word text="a" break_level="SPACE_BREAK"/>
  <word text="diamond" lemma="diamond" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1240094.001" break_level="SPACE_BREAK"/>
  <word text="studded" break_level="SPACE_BREAK"/>
  <word text="luxury" break_level="SPACE_BREAK"/>
  <word text="watch" lemma="watch" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1305222.010" break_level="SPACE_BREAK"/>
  <word text="strapped" lemma="strap" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1294827.005" break_level="SPACE_BREAK"/>
  <word text="around" break_level="SPACE_BREAK"/>
  <word text="your" break_level="SPACE_BREAK"/>
  <word text="wrist" lemma="wrist" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1307263.001" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="watch" lemma="watch" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1305222.001" break_level="SPACE_BREAK"/>
  <word text="everybody" break_level="SPACE_BREAK"/>
  <word text="stare" break_level="SPACE_BREAK"/>
  <word text="in" break_level="SPACE_BREAK"/>
  <word text="awe" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Business" break_level="SENTENCE_BREAK"/>
  <word text="colleagues" break_level="SPACE_BREAK"/>
  <word text="will" lemma="will" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1306429.001" break_level="SPACE_BREAK"/>
  <word text="envy" break_level="SPACE_BREAK"/>
  <word text="your" break_level="SPACE_BREAK"/>
  <word text="wealth" break_level="SPACE_BREAK"/>
  <word text=";" break_level="NO_BREAK"/>
  <word text="with" break_level="SPACE_BREAK"/>
  <word text="$" break_level="SPACE_BREAK"/>
  <word text="20,000" break_level="NO_BREAK"/>
  <word text="around" break_level="SPACE_BREAK"/>
  <word text="your" break_level="SPACE_BREAK"/>
  <word text="wrist" lemma="wrist" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1307263.001" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="success" break_level="SPACE_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="a" break_level="SPACE_BREAK"/>
  <word text="statement" break_level="SPACE_BREAK"/>
  <word text="is" lemma="be" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1225404.008" break_level="SPACE_BREAK"/>
  <word text="assured" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="With" break_level="SENTENCE_BREAK"/>
  <word text="famous" break_level="SPACE_BREAK"/>
  <word text="luxury" break_level="SPACE_BREAK"/>
  <word text="brands" lemma="brand" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1228470.001" break_level="SPACE_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="choose" break_level="SPACE_BREAK"/>
  <word text="from" break_level="SPACE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Rolex" break_level="SENTENCE_BREAK"/>
  <word text="Patek" break_level="LINE_BREAK"/>
  <word text="Cartier" break_level="LINE_BREAK"/>
  <word text="Breitling" break_level="LINE_BREAK"/>
  <word text="Bell" break_level="LINE_BREAK"/>
  <word text="&amp;" break_level="SPACE_BREAK"/>
  <word text="Ross" break_level="SPACE_BREAK"/>
  <word text="and" break_level="LINE_BREAK"/>
  <word text="more" break_level="SPACE_BREAK"/>
  <word text="than" break_level="SPACE_BREAK"/>
  <word text="two" break_level="SPACE_BREAK"/>
  <word text="dozen" lemma="dozen" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1241892.001" break_level="SPACE_BREAK"/>
  <word text="other" lemma="other" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1274198.001" break_level="SPACE_BREAK"/>
  <word text="designer" break_level="SPACE_BREAK"/>
  <word text="brands" lemma="brand" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1228470.001" break_level="SPACE_BREAK"/>
  <word text="-" break_level="SPACE_BREAK"/>
  <word text="what" break_level="SPACE_BREAK"/>
  <word text="are" break_level="SPACE_BREAK"/>
  <word text="you" break_level="SPACE_BREAK"/>
  <word text="waiting" lemma="wait" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1304874.001" break_level="SPACE_BREAK"/>
  <word text="for" break_level="SPACE_BREAK"/>
  <word text="?" break_level="NO_BREAK"/>
  <word text="Pay" lemma="pay" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1276209.001" break_level="SENTENCE_BREAK"/>
  <word text="only" lemma="only" pos="ADV" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1273443.001" break_level="SPACE_BREAK"/>
  <word text="$" break_level="SPACE_BREAK"/>
  <word text="99" break_level="NO_BREAK"/>
  <word text="for" break_level="SPACE_BREAK"/>
  <word text="watches" lemma="watch" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1305222.010" break_level="SPACE_BREAK"/>
  <word text="that" break_level="SPACE_BREAK"/>
  <word text="are" lemma="be" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1225404.008" break_level="SPACE_BREAK"/>
  <word text="worth" break_level="SPACE_BREAK"/>
  <word text="thousands" break_level="SPACE_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="thousands" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Shop" lemma="shop" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1290155.007" break_level="SENTENCE_BREAK"/>
  <word text="safely" break_level="SPACE_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="securely" break_level="SPACE_BREAK"/>
  <word text="online" break_level="SPACE_BREAK"/>
  <word text="in" break_level="SPACE_BREAK"/>
  <word text="2008" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="-" break_level="SENTENCE_BREAK"/>
  <word text="Visit" lemma="visit" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1304446.001" break_level="SPACE_BREAK"/>
  <word text="our" break_level="SPACE_BREAK"/>
  <word text="site" lemma="site" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1291008.004" break_level="SPACE_BREAK"/>
  <word text="-" break_level="SPACE_BREAK"/>
  <word text="www.mibnne.com" break_level="SPACE_BREAK"/>
</SimpleWsdDoc>
