=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/simple-wsd-doc.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT SimpleWsdDoc (word*) >
<!ATTLIST SimpleWsdDoc name CDATA #REQUIRED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word text CDATA #REQUIRED>
<!ATTLIST word break_level CDATA #REQUIRED>
<!ATTLIST word lemma CDATA #IMPLIED>
<!ATTLIST word pos CDATA #IMPLIED>
<!ATTLIST word sense CDATA #IMPLIED>

=== lbwbowenLi/Seq2Seq-on-Word-Sense-Disambiguition/seq2seq_pytorch/word_sense_disambigation_corpora-master/masc/written/spam/ucb45.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE SimpleWsdDoc SYSTEM "simple-wsd-doc.dtd">
<SimpleWsdDoc name="/written/spam/ucb45.txt">
  <word text="/" break_level="NO_BREAK"/>
  <word text="written" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="spam" lemma="spam" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1292742.002" break_level="NO_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
  <word text="ucb45.txt" break_level="NO_BREAK"/>
  <word text="From" break_level="PARAGRAPH_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="``" break_level="SPACE_BREAK"/>
  <word text="Backgammon" break_level="NO_BREAK"/>
  <word text="Room" break_level="SPACE_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="To" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Subject" lemma="subject" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1295267.001" break_level="LINE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="100" break_level="SPACE_BREAK"/>
  <word text="$" break_level="NO_BREAK"/>
  <word text="bonus" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Free" lemma="free" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1248904.015" break_level="SENTENCE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Date" lemma="date" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1238437.001" break_level="SENTENCE_BREAK"/>
  <word text=":" break_level="NO_BREAK"/>
  <word text="Mon" break_level="SENTENCE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="24" break_level="SPACE_BREAK"/>
  <word text="Sep" break_level="SPACE_BREAK"/>
  <word text="2007" break_level="SPACE_BREAK"/>
  <word text="21:18:48" break_level="SPACE_BREAK"/>
  <word text="+0000" break_level="SPACE_BREAK"/>
  <word text="OnlineBackgammonRoom" break_level="PARAGRAPH_BREAK"/>
  <word text="is" lemma="be" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1225404.008" break_level="SPACE_BREAK"/>
  <word text="giving" lemma="give" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1250951.001" break_level="SPACE_BREAK"/>
  <word text="away" break_level="SPACE_BREAK"/>
  <word text="Free" break_level="SPACE_BREAK"/>
  <word text="Money" break_level="SPACE_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="Not" break_level="PARAGRAPH_BREAK"/>
  <word text="only" lemma="only" pos="ADV" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1273443.001" break_level="SPACE_BREAK"/>
  <word text="are" lemma="be" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1225404.008" break_level="SPACE_BREAK"/>
  <word text="we" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="best" lemma="best" pos="ADJ" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1226116.001" break_level="SPACE_BREAK"/>
  <word text="place" lemma="place" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1278491.001" break_level="SPACE_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="play" lemma="play" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1278708.001" break_level="SPACE_BREAK"/>
  <word text="Backgammon" break_level="SPACE_BREAK"/>
  <word text="," break_level="NO_BREAK"/>
  <word text="we" break_level="SPACE_BREAK"/>
  <word text="are" break_level="SPACE_BREAK"/>
  <word text="also" break_level="SPACE_BREAK"/>
  <word text="giving" lemma="give" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1250951.001" break_level="SPACE_BREAK"/>
  <word text="you" break_level="SPACE_BREAK"/>
  <word text="$" break_level="SPACE_BREAK"/>
  <word text="100" break_level="NO_BREAK"/>
  <word text="FRE.E." break_level="SPACE_BREAK"/>
  <word text="All" break_level="PARAGRAPH_BREAK"/>
  <word text="you" break_level="SPACE_BREAK"/>
  <word text="need" break_level="SPACE_BREAK"/>
  <word text="to" break_level="SPACE_BREAK"/>
  <word text="do" lemma="do" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1241237.001" break_level="SPACE_BREAK"/>
  <word text="is" break_level="SPACE_BREAK"/>
  <word text="make" lemma="make" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1265484.008" break_level="SPACE_BREAK"/>
  <word text="a" break_level="SPACE_BREAK"/>
  <word text="minimum" break_level="SPACE_BREAK"/>
  <word text="$" break_level="SPACE_BREAK"/>
  <word text="100" break_level="NO_BREAK"/>
  <word text="First" break_level="SPACE_BREAK"/>
  <word text="Time" break_level="SPACE_BREAK"/>
  <word text="Depos1t" break_level="SPACE_BREAK"/>
  <word text="between" break_level="SPACE_BREAK"/>
  <word text="and" break_level="SPACE_BREAK"/>
  <word text="BGroom" break_level="SPACE_BREAK"/>
  <word text="will" lemma="will" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1306429.001" break_level="SPACE_BREAK"/>
  <word text="credit" lemma="credit" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1236949.015" break_level="SPACE_BREAK"/>
  <word text="your" break_level="SPACE_BREAK"/>
  <word text="account" lemma="account" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1219574.005" break_level="SPACE_BREAK"/>
  <word text="with" break_level="SPACE_BREAK"/>
  <word text="a" break_level="SPACE_BREAK"/>
  <word text="Free" break_level="SPACE_BREAK"/>
  <word text="~" break_level="NO_BREAK"/>
  <word text="$" break_level="NO_BREAK"/>
  <word text="100" break_level="NO_BREAK"/>
  <word text="~" break_level="NO_BREAK"/>
  <word text="bonus" break_level="NO_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="When" lemma="when" pos="ADV" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1305963.004" break_level="PARAGRAPH_BREAK"/>
  <word text="making" lemma="make" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1265484.008" break_level="SPACE_BREAK"/>
  <word text="your" break_level="SPACE_BREAK"/>
  <word text="depos1t" break_level="SPACE_BREAK"/>
  <word text="please" break_level="SPACE_BREAK"/>
  <word text="enter" lemma="enter" pos="VERB" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1244298.012" break_level="SPACE_BREAK"/>
  <word text="the" break_level="SPACE_BREAK"/>
  <word text="code" lemma="code" pos="NOUN" sense="/dictionary/sense/en_us_NOAD3e_2012/m_en_us1234174.001" break_level="SPACE_BREAK"/>
  <word text="``" break_level="SPACE_BREAK"/>
  <word text="FIRST" break_level="NO_BREAK"/>
  <word text="$" break_level="NO_BREAK"/>
  <word text="100" break_level="NO_BREAK"/>
  <word text="&#39;&#39;" break_level="NO_BREAK"/>
  <word text="." break_level="NO_BREAK"/>
  <word text="http://www.webbackgammon.org" break_level="PARAGRAPH_BREAK"/>
  <word text="/" break_level="NO_BREAK"/>
</SimpleWsdDoc>
